### ISSUE TITLE
Missing `Metadata` messages in google.cloud.speech.v1beta1

### ISSUE THREAD

**Issue by akashkrishnan** [googleapis/googleapis#137]
For example, the message [AsyncRecognizeMetadata](https://cloud.google.com/speech/reference/rpc/google.cloud.speech.v1beta1#google.cloud.speech.v1beta1.AsyncRecognizeMetadata) is not defined in the proto file [cloud_speech.proto](https://github.com/googleapis/googleapis/blob/master/google/cloud/speech/v1beta1/cloud_speech.proto). Is there a way to retrieve the messages or is there an example of how to generate the appropriate message as described by the documentation?

EDIT:

Would the following be valid and correct?

``` proto
import "google/protobuf/timestamp.proto";

message AsyncRecognizeMetadata {
  int32 progress_percent = 1;
  google.protobuf.Timestamp start_time = 2;
  google.protobuf.Timestamp last_update_time = 3;
}
```

**Comment by geigerj** [comment]
I think this was because the proto stored in this repo was out of date; we now have better tooling to keep the protos up-to-date. The message seems to have been added here: https://github.com/googleapis/googleapis/blob/07d1887d6dc71a06ce52f29a65a555dba13cf3b5/google/cloud/speech/v1beta1/cloud_speech.proto#L63
