### ISSUE TITLE
RGB values are defined as floats instead of integers.

### ISSUE THREAD

**Issue by daspecster** [googleapis/googleapis#242]
RGB values are intended to be integers and the HTTP/JSON response from the [Vision API contains the correct values](https://cloud.google.com/vision/docs/detecting-properties).

The gRPC/protobuf version however has the RGB values set to floats and documented as [0, 1] values.
See:
https://github.com/googleapis/googleapis/blob/c329e5b1723111925ac81458955eaeccdf6ebb4d/google/type/color.proto#L142-L164

**Comment by wora** [comment]
The google.type package is not part of protobuf. It contains standard types
shared by Google APIs. They have good design quality and full commitment of
no breaking change. Everyone us welcome to use them. Because the types need
to work with many languages, it may not match existing standard used by
other system.

**Comment by daspecster** [comment]
@wora ok thanks. I'll see if I can get in touch with some of the Vision API folks.
